# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pylook/ui/pylook.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.VerticalTabs)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.figures_tab_dock = TabWidget(self.centralwidget)
        self.figures_tab_dock.setObjectName("figures_tab_dock")
        self.start_tab = QtWidgets.QWidget()
        self.start_tab.setObjectName("start_tab")
        self.figures_tab_dock.addTab(self.start_tab, "")
        self.verticalLayout.addWidget(self.figures_tab_dock)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.data_dock = QtWidgets.QDockWidget(MainWindow)
        self.data_dock.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.data_dock.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea)
        self.data_dock.setObjectName("data_dock")
        self.data_widget = QtWidgets.QWidget()
        self.data_widget.setObjectName("data_widget")
        self.data_layout = QtWidgets.QVBoxLayout(self.data_widget)
        self.data_layout.setObjectName("data_layout")
        self.data_tree = DataTree(self.data_widget)
        self.data_tree.setWordWrap(True)
        self.data_tree.setObjectName("data_tree")
        self.data_tree.headerItem().setText(0, "1")
        self.data_layout.addWidget(self.data_tree)
        self.filter_layout = QtWidgets.QHBoxLayout()
        self.filter_layout.setObjectName("filter_layout")
        self.label = QtWidgets.QLabel(self.data_widget)
        self.label.setObjectName("label")
        self.filter_layout.addWidget(self.label)
        self.data_regexp = QtWidgets.QLineEdit(self.data_widget)
        self.data_regexp.setObjectName("data_regexp")
        self.filter_layout.addWidget(self.data_regexp)
        self.data_layout.addLayout(self.filter_layout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.data_widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.var_regexp = QtWidgets.QLineEdit(self.data_widget)
        self.var_regexp.setObjectName("var_regexp")
        self.horizontalLayout.addWidget(self.var_regexp)
        self.data_layout.addLayout(self.horizontalLayout)
        self.data_dock.setWidget(self.data_widget)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.data_dock)
        self.figures_dock = QtWidgets.QDockWidget(MainWindow)
        self.figures_dock.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.figures_dock.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea)
        self.figures_dock.setObjectName("figures_dock")
        self.figures_widget = QtWidgets.QWidget()
        self.figures_widget.setObjectName("figures_widget")
        self.figures_layout = QtWidgets.QVBoxLayout(self.figures_widget)
        self.figures_layout.setObjectName("figures_layout")
        self.figures_tree = FiguresTree(self.figures_widget)
        self.figures_tree.setAutoFillBackground(False)
        self.figures_tree.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.figures_tree.setAlternatingRowColors(True)
        self.figures_tree.setIndentation(10)
        self.figures_tree.setAllColumnsShowFocus(False)
        self.figures_tree.setWordWrap(True)
        self.figures_tree.setObjectName("figures_tree")
        self.figures_tree.headerItem().setText(0, "key")
        item_0 = QtWidgets.QTreeWidgetItem(self.figures_tree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.figures_layout.addWidget(self.figures_tree)
        self.figures_dock.setWidget(self.figures_widget)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.figures_dock)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.figures_tab_dock.setCurrentIndex(0)
        self.data_regexp.textChanged['QString'].connect(self.data_tree.update)
        self.var_regexp.textChanged['QString'].connect(self.data_tree.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.data_tree, self.figures_tree)
        MainWindow.setTabOrder(self.figures_tree, self.figures_tab_dock)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.figures_tab_dock.setTabText(self.figures_tab_dock.indexOf(self.start_tab), _translate("MainWindow", "Tab 1"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.data_dock.setWindowTitle(_translate("MainWindow", "Data Store"))
        self.label.setText(_translate("MainWindow", "Files"))
        self.data_regexp.setText(_translate("MainWindow", "*"))
        self.label_2.setText(_translate("MainWindow", "Var"))
        self.figures_dock.setWindowTitle(_translate("MainWindow", "Figures"))
        self.figures_tree.setSortingEnabled(True)
        self.figures_tree.headerItem().setText(1, _translate("MainWindow", "value"))
        __sortingEnabled = self.figures_tree.isSortingEnabled()
        self.figures_tree.setSortingEnabled(False)
        self.figures_tree.topLevelItem(0).setText(0, _translate("MainWindow", "All"))
        self.figures_tree.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "urcrnrlon"))
        self.figures_tree.topLevelItem(0).child(0).setText(1, _translate("MainWindow", "180"))
        self.figures_tree.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "urcrnlat"))
        self.figures_tree.topLevelItem(0).child(1).setText(1, _translate("MainWindow", "90"))
        self.figures_tree.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "llcrnrlon"))
        self.figures_tree.topLevelItem(0).child(2).setText(1, _translate("MainWindow", "-180"))
        self.figures_tree.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "llcrnrlat"))
        self.figures_tree.topLevelItem(0).child(3).setText(1, _translate("MainWindow", "-90"))
        self.figures_tree.setSortingEnabled(__sortingEnabled)
        self.actionOpen.setText(_translate("MainWindow", "Open"))

from .data_tree import DataTree
from .figures_tree import FiguresTree
from .tabs import TabWidget
